version: '2.1'

services:
  gateway:
    build:
      context: ../opg-sirius-api-gateway/
    volumes:
      - ../opg-sirius-api-gateway/docker:/srv/docker:cached
      - ../opg-sirius-api-gateway/lambdas:/srv/lambdas:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LAMBDAS_PATH: ${PWD}/../opg-sirius-api-gateway/lambdas
      PASSTHROUGH_DATA_PROVIDER: json

  localstack-config:
    build:
      context: ../opg-sirius-api-gateway/
    volumes:
      - ../opg-sirius-api-gateway/localstack-config:/config

