openapi: 3.0.0
info:
  version: '2.0.0'
  title: 'OPG Data API'
  description: 'Access to OPG Data'
  contact:
    name: API Support
    # url: "http://www.example.com/support"
    # email: "support@example.com"

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/leapday/opg-data/1.0.0

tags:
  - name: deputy-reporting
    description: API operations relating to the deputy-reporting integration
    externalDocs:
      url: https://github.com/ministryofjustice/opg-data-deputy-reporting

paths:
  '/reports/{id}':
    description: Client report
    get:
      summary: Client report
      description: Client report
      operationId: showReportDocument
      tags:
        - 'deputy-reporting'
      parameters:
        - in: path
          name: id
          required: true
          description: Report UUID
          schema:
            $ref: '#/components/schemas/ReportId'
      responses:
        '200':
          description: Client report
          content:
            application/vnd.opg-data.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Report'
                  links:
                    type: object
                  meta:
                    type: object
  '/clients/{caseref}/reports':
    description: Client reports
    post:
      summary: Add a client report file
      description: Add a client report file
      operationId: addReportDocument
      tags:
        - 'deputy-reporting'
      parameters:
        - in: path
          name: caseref
          required: true
          description: Case Reference / Casrec number
          schema:
            type: string
            pattern: '^([0-9]{7}T|[0-9]{8})$'
            example: '0319392T'
      requestBody:
        required: true
        description: A report pdf file, and metadata
        content:
          multipart/related:
            schema:
              type: object
              properties:
                report:
                  type: object
                  required:
                    - data
                  properties:
                    data:
                      $ref: '#/components/schemas/Report'
                report_file:
                  type: string
                  format: base64
            encoding:
              report:
                contentType: application/vnd.opg-data.v1+json
              report_file:
                contentType: application/pdf
      responses:
        '201':
          description: Document created
          content:
            application/vnd.opg-data.v1+json:
              schema:
                type: object
                required:
                  - data
                  - links
                properties:
                  data:
                    $ref: '#/components/schemas/Report'
                  links:
                    type: object
                    properties:
                      api-docs:
                        type: string
                        format: uri
                        example: 'https://opg-data-api.service.gov.uk/developer/'
                  meta:
                    type: object
        '400':
          description: Generic bad request (generally invalid syntax)
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error400'
        '401':
          description: Unauthorised (no current user and there should be)
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden - The current user is forbidden from accessing this data (in this way)
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error403'
        '404':
          description: That URL is not a valid route, or the item resource does not exist
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error404'
        '413':
          description: Payload too large
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error413'
        '415':
          description: Unsupported media type
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error415'
        '500':
          description: Something unexpected happened and it is the API's fault
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error500'
        '503':
          description: Service Unavailable - please try again later
          content:
            application/vnd.opg-data.v1+json:
              schema: 
                $ref: '#/components/schemas/Error503'
  '/reports/{id}/supportingdocuments':
    description: Supporting documents associated with client reports
    post:
      summary: Add a document to Supervision which supports a report
      description: Add a document to Supervision which supports a report
      operationId: addReportSupportingDocument
      tags:
        - 'deputy-reporting'
      parameters:
        - in: path
          name: id
          required: true
          description: Report UUID
          schema:
            $ref: '#/components/schemas/ReportId'
      requestBody:
        required: true
        description: The supporting document
        content:
          image/*:
            schema:
              type: string
              format: binary
          application/*:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: Document created
          content:
            application/vnd.opg-data.v1+json:
              schema:
                type: object
                required:
                  - data
                  - links
                properties:
                  data:
                    $ref: '#/components/schemas/ReportSupportingDocument'
                  links:
                    type: object
                    properties:
                      api-docs:
                        type: string
                        format: uri
                        example: 'https://opg-data-api.service.gov.uk/developer/'
                  meta:
                    type: object
components:
  schemas:
    Report:
      type: object
      required:
        - type
        - id
        - attributes
        - links
      properties:
        type:
          type: string
          pattern: '^reports$'
          example: reports
        id:
          $ref: '#/components/schemas/ReportId'
        attributes:
          type: object
          required:
            - reporting_period_from
            - reporting_period_to
            - year
            - date_submitted
            - type
          properties:
            reporting_period_from:
              type: string
              format: date
              example: '2019-01-01'
            reporting_period_to:
              type: string
              format: date
              example: '2019-12-31'
            year:
              type: integer
              format: int32
              minimum: 999
              maximum: 9999
              example: 2019
            date_submitted:
              type: string
              format: date-time
              example: '2020-01-03T09:30:00.001Z'
            type:
              type: string
              enum:
                - 'PF'
                - 'HW'
                - 'NDR'
              example: 'PF'
        links:
          type: object
          readOnly: true
          required:
            - self
          properties:
            self:
              type: string
              format: uri
              example: 'https://opg-data-api.service.gov.uk/reports/5a8b1a26-8296-4373-ae61-f8d0b250e773'
            client:
              type: string
              format: uri
              example: 'https://opg-data-api.service.gov.uk/clients/0319392T'
    ReportSupportingDocument:
      type: object
      required:
        - type
        - id
        - links
      properties:
        type:
          type: string
          pattern: '^supportingdocuments$'
          example: supportingdocuments
        id:
          $ref: '#/components/schemas/ReportId'
        links:
          type: object
          readOnly: true
          required:
            - self
          properties:
            self:
              type: string
              format: uri
              example: 'https://opg-data-api.service.gov.uk/reports/5a8b1a26-8296-4373-ae61-f8d0b250e773/supportingdocuments/5a8b1a26-8296-4373-ae61-f8d0b250e774'
            report:
              type: string
              format: uri
              example: 'https://opg-data-api.service.gov.uk/reports/5a8b1a26-8296-4373-ae61-f8d0b250e773'
    ReportId:
      type: string
      readOnly: true
      format: uuid
      description: Document UUID
      pattern: '^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$'
      example: '5a8b1a26-8296-4373-ae61-f8d0b250e773'
    Error400:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error401:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error403:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error404:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error413:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error415:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error500:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
    Error503:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
            properties:
              id:
                type: string
                example: 'A123BCD'
              code:
                type: string
                example: 'OPGDATA-API-FORBIDDEN'
              title:
                type: string
                example: 'User Lacks Permissions'
              detail:
                type: string
                example: 'You are not authorised to perform the selected action(s) on this resource'
              links:
                type: object
                properties:
                  about:
                    type: string
                    format: uri
                    example: 'https://opg-data-api.service.gov.uk/help/errors/forbidden'
              source:
                type: object
                properties:
                  parameter:
                    type: string
                    example: 'clientref'
                  pointer:
                    type: string
                    example: '/data/attributes/date_submitted'
                    